[package]
name = "legbone"
version = "0.1.0"
authors = ["Ricardo"]
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
num_enum = "0.6"
crossbeam-queue = "0.3"
flume = "0.10"
byteorder_async = { git="https://github.com/rsribeiro/byteorder_async", features=["futures_async"] }
futures = "0.3"
async-trait = "0.1"
once_cell = "1.17"
anyhow = "1.0"
toml = "0.7"
serde = "1.0"
serde_derive = "1.0"

[dependencies.async-std]
version = "1.12"
features = ["attributes", "unstable"]

[dependencies.clap]
version = "4.3"
features = ["derive"]
