[package]
name = "legbone"
version = "0.1.0"
authors = ["Ricardo"]
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.9.0"
num_enum = "0.5.4"
crossbeam-queue = "0.3.2"
flume = "0.10.9"
byteorder_async = { git="https://github.com/rsribeiro/byteorder_async", features=["futures_async"] }
futures = "0.3.18"
async-trait = "0.1.52"
once_cell = "1.8.0"
anyhow = "1.0"

[dependencies.async-std]
version = "1.10"
features = ["attributes", "unstable"]

[dependencies.clap]
version = "3.0.4"
features = ["derive"]