[package]
name = "legbone"
version = "0.1.0"
authors = ["Ricardo"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7.1"
num_enum = "0.5.1"
crossbeam-queue = "0.2.3"
flume = "0.9.2"
byteorder_async = { git="https://github.com/rsribeiro/byteorder_async", features=["futures_async"] }
futures = "0.3.0"
async-trait = "0.1.38"
once_cell = "1.5.2"
anyhow = "1.0"
clap = "3.0.0-beta.2"

[dependencies.async-std]
version = "1.8"
features = ["attributes", "unstable"]